
server:
  port: 6005
spring:
  application:
    name: service-quartz
  cloud:
    config:
      profile: test
      discovery:
        enabled: true
        service-id: service-config
  datasource:
    url: jdbc:mysql://192.168.0.32:3306/hu_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://localhost:6001/eureka
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
